// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyZeroBlog.EntityFrameworkCore;

namespace SyZeroBlog.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SyZeroBlogDbContext))]
    [Migration("20200301113007_1.0")]
    partial class _10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SyZero.Domain.Entities.Config", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("SyZeroBlog.Core.Authorization.Users.User", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("LastIP");

                    b.Property<DateTime?>("LastTime");

                    b.Property<int>("Level");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("NickName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<long>("PictureId");

                    b.Property<int>("Sex");

                    b.Property<int>("Status");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SyZeroBlog.Core.File.File", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<long>("CreateUserId");

                    b.Property<string>("From");

                    b.Property<string>("Name");

                    b.Property<int>("Size");

                    b.Property<string>("SourceName");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId")
                        .IsUnique();

                    b.ToTable("File");
                });

            modelBuilder.Entity("SyZeroBlog.Core.File.File", b =>
                {
                    b.HasOne("SyZeroBlog.Core.Authorization.Users.User", "CreateUser")
                        .WithOne("HeadPicture")
                        .HasForeignKey("SyZeroBlog.Core.File.File", "CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
