// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyZero.Infrastructure.EntityFramework;

namespace SyZero.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(SyDbContext))]
    [Migration("20190315162030_SYZERO2.1")]
    partial class SYZERO21
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SyZero.Domain.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Author");

                    b.Property<long>("Category");

                    b.Property<int>("ClickCount");

                    b.Property<string>("Content");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int>("FabulousCount");

                    b.Property<string>("Picture");

                    b.Property<string>("SEODescription");

                    b.Property<string>("SEOKeywords");

                    b.Property<string>("SEOTitle");

                    b.Property<int>("ScoreCount");

                    b.Property<int>("ShareCount");

                    b.Property<int>("State");

                    b.Property<string>("Tags");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.Property<string>("TypeCode");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SyZero.Domain.Model.ArticleCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Content");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<long>("ParentID");

                    b.Property<string>("Picture");

                    b.Property<int>("State");

                    b.Property<string>("Tags");

                    b.Property<string>("TypeCode");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("ArticleCategory");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<long>("ArticleID");

                    b.Property<string>("Content");

                    b.Property<int>("FabulousCount");

                    b.Property<long>("ParentID");

                    b.Property<string>("Picture");

                    b.Property<int>("State");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<long>("UserID");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Content");

                    b.Property<string>("Messages");

                    b.Property<long>("ParentID");

                    b.Property<string>("Picture");

                    b.Property<int>("State");

                    b.Property<string>("TypeCode");

                    b.Property<long>("UserID");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("SyZero.Domain.Model.SiteConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Description");

                    b.Property<string>("Key");

                    b.Property<long>("ParentID");

                    b.Property<string>("Picture");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("SiteConfig");
                });

            modelBuilder.Entity("SyZero.Domain.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<DateTime>("LastTime");

                    b.Property<string>("Mail")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .HasMaxLength(200);

                    b.Property<string>("Photo")
                        .HasMaxLength(1000);

                    b.Property<int>("Sex");

                    b.Property<int>("State");

                    b.Property<int>("Utype");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
